#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  tasks:
    - file:
        path: "{{ lookup('env','HOME') }}/.ansible/roles/"
        state: absent
    - local_action:
        command ansible-galaxy install -r requirements.yaml
