#!/usr/bin/env ansible-playbook
---
- name: "Illallangi Alfa"
  hosts: 
    - "k8s"
  order: sorted
  roles:
    - "configure-hostname"
    - "configure-hosts"

    - "configure-nfs"
    - "configure-lm-sensors"
    - "configure-kubernetes"
    - "configure-bmon"
    - "configure-htop"
    - "configure-nethogs"
    - "configure-tmux"
    - "configure-rsync"

    - "deploy-lb"
    - "deploy-storage"
    - "deploy-powerdns"

    - "update-packages"
